# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: layer/layer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='layer/layer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11layer/layer.proto\"Y\n\x05Layer\x12\x1e\n\x04type\x18\x01 \x03(\x0e\x32\x10.Layer.LayerType\"0\n\tLayerType\x12\x0b\n\x07\x46LATTEN\x10\x00\x12\t\n\x05\x44\x45NSE\x10\x01\x12\x0b\n\x07\x44ROPOUT\x10\x02\"\x95\x03\n\x15SequentialModelLayers\x12\x16\n\x06layers\x18\x01 \x03(\x0b\x32\x06.Layer\x12:\n\rflattenLayers\x18\x02 \x03(\x0b\x32#.SequentialModelLayers.FlattenLayer\x12\x36\n\x0b\x64\x65nseLayers\x18\x03 \x03(\x0b\x32!.SequentialModelLayers.DenseLayer\x12:\n\rdropoutLayers\x18\x04 \x03(\x0b\x32#.SequentialModelLayers.DropoutLayer\x1a\x16\n\x05Shape\x12\r\n\x05shape\x18\x01 \x03(\x05\x1a<\n\x0c\x46lattenLayer\x12,\n\x06shapes\x18\x01 \x03(\x0b\x32\x1c.SequentialModelLayers.Shape\x1a?\n\nDenseLayer\x12\r\n\x05units\x18\x01 \x03(\x05\x12\x13\n\x0b\x61\x63tivations\x18\x02 \x03(\t\x12\r\n\x05names\x18\x03 \x03(\t\x1a\x1d\n\x0c\x44ropoutLayer\x12\r\n\x05ratio\x18\x01 \x03(\x02\x62\x06proto3'
)



_LAYER_LAYERTYPE = _descriptor.EnumDescriptor(
  name='LayerType',
  full_name='Layer.LayerType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLATTEN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DENSE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DROPOUT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=62,
  serialized_end=110,
)
_sym_db.RegisterEnumDescriptor(_LAYER_LAYERTYPE)


_LAYER = _descriptor.Descriptor(
  name='Layer',
  full_name='Layer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Layer.type', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LAYER_LAYERTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=110,
)


_SEQUENTIALMODELLAYERS_SHAPE = _descriptor.Descriptor(
  name='Shape',
  full_name='SequentialModelLayers.Shape',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape', full_name='SequentialModelLayers.Shape.shape', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=360,
)

_SEQUENTIALMODELLAYERS_FLATTENLAYER = _descriptor.Descriptor(
  name='FlattenLayer',
  full_name='SequentialModelLayers.FlattenLayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='shapes', full_name='SequentialModelLayers.FlattenLayer.shapes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=422,
)

_SEQUENTIALMODELLAYERS_DENSELAYER = _descriptor.Descriptor(
  name='DenseLayer',
  full_name='SequentialModelLayers.DenseLayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='units', full_name='SequentialModelLayers.DenseLayer.units', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='activations', full_name='SequentialModelLayers.DenseLayer.activations', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='names', full_name='SequentialModelLayers.DenseLayer.names', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=487,
)

_SEQUENTIALMODELLAYERS_DROPOUTLAYER = _descriptor.Descriptor(
  name='DropoutLayer',
  full_name='SequentialModelLayers.DropoutLayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ratio', full_name='SequentialModelLayers.DropoutLayer.ratio', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=489,
  serialized_end=518,
)

_SEQUENTIALMODELLAYERS = _descriptor.Descriptor(
  name='SequentialModelLayers',
  full_name='SequentialModelLayers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='layers', full_name='SequentialModelLayers.layers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flattenLayers', full_name='SequentialModelLayers.flattenLayers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='denseLayers', full_name='SequentialModelLayers.denseLayers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dropoutLayers', full_name='SequentialModelLayers.dropoutLayers', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SEQUENTIALMODELLAYERS_SHAPE, _SEQUENTIALMODELLAYERS_FLATTENLAYER, _SEQUENTIALMODELLAYERS_DENSELAYER, _SEQUENTIALMODELLAYERS_DROPOUTLAYER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=518,
)

_LAYER.fields_by_name['type'].enum_type = _LAYER_LAYERTYPE
_LAYER_LAYERTYPE.containing_type = _LAYER
_SEQUENTIALMODELLAYERS_SHAPE.containing_type = _SEQUENTIALMODELLAYERS
_SEQUENTIALMODELLAYERS_FLATTENLAYER.fields_by_name['shapes'].message_type = _SEQUENTIALMODELLAYERS_SHAPE
_SEQUENTIALMODELLAYERS_FLATTENLAYER.containing_type = _SEQUENTIALMODELLAYERS
_SEQUENTIALMODELLAYERS_DENSELAYER.containing_type = _SEQUENTIALMODELLAYERS
_SEQUENTIALMODELLAYERS_DROPOUTLAYER.containing_type = _SEQUENTIALMODELLAYERS
_SEQUENTIALMODELLAYERS.fields_by_name['layers'].message_type = _LAYER
_SEQUENTIALMODELLAYERS.fields_by_name['flattenLayers'].message_type = _SEQUENTIALMODELLAYERS_FLATTENLAYER
_SEQUENTIALMODELLAYERS.fields_by_name['denseLayers'].message_type = _SEQUENTIALMODELLAYERS_DENSELAYER
_SEQUENTIALMODELLAYERS.fields_by_name['dropoutLayers'].message_type = _SEQUENTIALMODELLAYERS_DROPOUTLAYER
DESCRIPTOR.message_types_by_name['Layer'] = _LAYER
DESCRIPTOR.message_types_by_name['SequentialModelLayers'] = _SEQUENTIALMODELLAYERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Layer = _reflection.GeneratedProtocolMessageType('Layer', (_message.Message,), {
  'DESCRIPTOR' : _LAYER,
  '__module__' : 'layer.layer_pb2'
  # @@protoc_insertion_point(class_scope:Layer)
  })
_sym_db.RegisterMessage(Layer)

SequentialModelLayers = _reflection.GeneratedProtocolMessageType('SequentialModelLayers', (_message.Message,), {

  'Shape' : _reflection.GeneratedProtocolMessageType('Shape', (_message.Message,), {
    'DESCRIPTOR' : _SEQUENTIALMODELLAYERS_SHAPE,
    '__module__' : 'layer.layer_pb2'
    # @@protoc_insertion_point(class_scope:SequentialModelLayers.Shape)
    })
  ,

  'FlattenLayer' : _reflection.GeneratedProtocolMessageType('FlattenLayer', (_message.Message,), {
    'DESCRIPTOR' : _SEQUENTIALMODELLAYERS_FLATTENLAYER,
    '__module__' : 'layer.layer_pb2'
    # @@protoc_insertion_point(class_scope:SequentialModelLayers.FlattenLayer)
    })
  ,

  'DenseLayer' : _reflection.GeneratedProtocolMessageType('DenseLayer', (_message.Message,), {
    'DESCRIPTOR' : _SEQUENTIALMODELLAYERS_DENSELAYER,
    '__module__' : 'layer.layer_pb2'
    # @@protoc_insertion_point(class_scope:SequentialModelLayers.DenseLayer)
    })
  ,

  'DropoutLayer' : _reflection.GeneratedProtocolMessageType('DropoutLayer', (_message.Message,), {
    'DESCRIPTOR' : _SEQUENTIALMODELLAYERS_DROPOUTLAYER,
    '__module__' : 'layer.layer_pb2'
    # @@protoc_insertion_point(class_scope:SequentialModelLayers.DropoutLayer)
    })
  ,
  'DESCRIPTOR' : _SEQUENTIALMODELLAYERS,
  '__module__' : 'layer.layer_pb2'
  # @@protoc_insertion_point(class_scope:SequentialModelLayers)
  })
_sym_db.RegisterMessage(SequentialModelLayers)
_sym_db.RegisterMessage(SequentialModelLayers.Shape)
_sym_db.RegisterMessage(SequentialModelLayers.FlattenLayer)
_sym_db.RegisterMessage(SequentialModelLayers.DenseLayer)
_sym_db.RegisterMessage(SequentialModelLayers.DropoutLayer)


# @@protoc_insertion_point(module_scope)
